services:
  coding-guru:
    build:
      context: .
      dockerfile: Dockerfile
    image: hridayesh68/coding-guru:latest
    container_name: coding-guru-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - coding_guru_data:/app/db/data

volumes:
  coding_guru_data:
    driver: local
